[build]
  command = "npm run build"
  publish = "client/build"

[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_VERSION = "9.0.0"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"

